// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://samiqjpidsvkfjmnzxwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbWlxanBpZHN2a2ZqbW56eHdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzMyODAsImV4cCI6MjA2ODg0OTI4MH0.yxbcf4f5HLCYd_bCjCSawFRk2-p8Ae6m_FAYlvwr6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});